=== mtsvilik/construction-company-xml/src/main/resources/companyforstax.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bankAccount">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="accountNumber" type="xs:positiveInteger"/>
                            <xs:element name="dateOfCreate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="customers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="customer" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstName" type="xs:string"/>
                                        <xs:element name="lastName" type="xs:string"/>
                                        <xs:element name="passport">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="passportNumber" type="xs:positiveInteger"/>
                                                    <xs:element name="dateOfIssue" type="xs:date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="budget" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="buildingMaterials">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="buildingMaterial" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="quantity" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mtsvilik/construction-company-xml/src/main/resources/companyforstax.xml
<?xml version="1.0" encoding="UTF-8"?>

<company name="KMK-INVEST" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="companyforstax.xsd">
    <bankAccount>
        <accountNumber>6896745</accountNumber>
        <dateOfCreate>2011-10-11</dateOfCreate>
    </bankAccount>
    <customers>
        <customer>
            <firstName>Ivan</firstName>
            <lastName>Petrov</lastName>
            <passport>
                <passportNumber>345678</passportNumber>
                <dateOfIssue>2014-10-14</dateOfIssue>
            </passport>
            <budget>50000</budget>
        </customer>
        <customer>
            <firstName>Mihail</firstName>
            <lastName>Ivanov</lastName>
            <passport>
                <passportNumber>876543</passportNumber>
                <dateOfIssue>2011-12-13</dateOfIssue>
            </passport>
            <budget>200000</budget>
        </customer>
    </customers>
    <buildingMaterials>
        <buildingMaterial>
            <title>Concrete</title>
            <quantity>200</quantity>
        </buildingMaterial>
        <buildingMaterial>
            <title>Wood</title>
            <quantity>500</quantity>
        </buildingMaterial>
        <buildingMaterial>
            <title>Metal</title>
            <quantity>1000</quantity>
        </buildingMaterial>
    </buildingMaterials>
</company>
