=== mtsvilik/construction-company-xml/src/main/resources/companyforjaxb.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="address">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="city" type="xs:string"/>
                            <xs:element name="street" type="xs:string"/>
                            <xs:element name="houseNumber" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="bankAccount">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="accountNumber" type="xs:positiveInteger"/>
                            <xs:element name="dateOfCreate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="customers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="customer" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstName" type="xs:string"/>
                                        <xs:element name="lastName" type="xs:string"/>
                                        <xs:element name="address">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="city" type="xs:string"/>
                                                    <xs:element name="street" type="xs:string"/>
                                                    <xs:element name="houseNumber" type="xs:positiveInteger"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="passport">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="passportNumber" type="xs:positiveInteger"/>
                                                    <xs:element name="dateOfIssue" type="xs:date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="budget" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="employees">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employee" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstName" type="xs:string"/>
                                        <xs:element name="lastName" type="xs:string"/>
                                        <xs:element name="address">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="city" type="xs:string"/>
                                                    <xs:element name="street" type="xs:string"/>
                                                    <xs:element name="houseNumber" type="xs:positiveInteger"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="passport">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="passportNumber" type="xs:positiveInteger"/>
                                                    <xs:element name="dateOfIssue" type="xs:date"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="position" type="xs:string"/>
                                        <xs:element name="salary" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="projects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="project" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="foundationDate" type="xs:date"/>
                                        <xs:element name="price" type="xs:decimal"/>
                                        <xs:element name="square" type="xs:positiveInteger"/>
                                        <xs:element name="numberOfRooms" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="buildingMaterials">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="buildingMaterial" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="quantity" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="equipments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipment" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="dateOfRelease" type="xs:date"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vehicles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="vehicle" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="engine" type="xs:string"/>
                                        <xs:element name="dateOfRelease" type="xs:date"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mtsvilik/construction-company-xml/src/main/resources/companyforjaxb.xml
<?xml version="1.0" encoding="UTF-8"?>

<company name="KMK-INVEST" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="companyforjaxb.xsd">
    <address>
        <city>Minsk</city>
        <street>Nemiga</street>
        <houseNumber>5</houseNumber>
    </address>
    <bankAccount>
        <accountNumber>6896745</accountNumber>
        <dateOfCreate>2011-10-11</dateOfCreate>
    </bankAccount>
    <customers>
        <customer>
            <firstName>Ivan</firstName>
            <lastName>Petrov</lastName>
            <address>
                <city>Minsk</city>
                <street>Kosmonavtov</street>
                <houseNumber>14</houseNumber>
            </address>
            <passport>
                <passportNumber>345678</passportNumber>
                <dateOfIssue>2014-10-14</dateOfIssue>
            </passport>
            <budget>50000</budget>
        </customer>
        <customer>
            <firstName>Mihail</firstName>
            <lastName>Ivanov</lastName>
            <address>
                <city>Minsk</city>
                <street>Esenina</street>
                <houseNumber>30</houseNumber>
            </address>
            <passport>
                <passportNumber>876543</passportNumber>
                <dateOfIssue>2011-12-13</dateOfIssue>
            </passport>
            <budget>200000</budget>
        </customer>
    </customers>
    <employees>
        <employee>
            <firstName>Oleg</firstName>
            <lastName>Sergeev</lastName>
            <address>
                <city>Minsk</city>
                <street>Krasnaya</street>
                <houseNumber>30</houseNumber>
            </address>
            <passport>
                <passportNumber>111543</passportNumber>
                <dateOfIssue>2015-12-13</dateOfIssue>
            </passport>
            <position>Manager</position>
            <salary>1500</salary>
        </employee>
        <employee>
            <firstName>Olga</firstName>
            <lastName>Maksimova</lastName>
            <address>
                <city>Minsk</city>
                <street>Slobodskaya</street>
                <houseNumber>113</houseNumber>
            </address>
            <passport>
                <passportNumber>734543</passportNumber>
                <dateOfIssue>2018-12-01</dateOfIssue>
            </passport>
            <position>Accountant</position>
            <salary>1250</salary>
        </employee>
    </employees>
    <projects>
        <project>
            <title>Green House</title>
            <foundationDate>2020-12-12</foundationDate>
            <price>150000</price>
            <square>105</square>
            <numberOfRooms>5</numberOfRooms>
        </project>
        <project>
            <title>White House</title>
            <foundationDate>2022-01-12</foundationDate>
            <price>300000</price>
            <square>215</square>
            <numberOfRooms>8</numberOfRooms>
        </project>
    </projects>
    <buildingMaterials>
        <buildingMaterial>
            <title>Concrete</title>
            <quantity>200</quantity>
        </buildingMaterial>
        <buildingMaterial>
            <title>Wood</title>
            <quantity>500</quantity>
        </buildingMaterial>
        <buildingMaterial>
            <title>Metal</title>
            <quantity>1000</quantity>
        </buildingMaterial>
    </buildingMaterials>
    <equipments>
        <equipment>
            <title>Crane tower</title>
            <dateOfRelease>2015-11-13</dateOfRelease>
        </equipment>
        <equipment>
            <title>Mixer concrete</title>
            <dateOfRelease>2013-11-12</dateOfRelease>
        </equipment>
        <equipment>
            <title>Generator</title>
            <dateOfRelease>2018-11-13</dateOfRelease>
        </equipment>
    </equipments>
    <vehicles>
        <vehicle>
            <title>Mercedes Benz</title>
            <engine>V8</engine>
            <dateOfRelease>2020-03-10</dateOfRelease>
        </vehicle>
        <vehicle>
            <title>Volkswagen Transporter</title>
            <engine>V3</engine>
            <dateOfRelease>2026-03-15</dateOfRelease>
        </vehicle>
        <vehicle>
            <title>BMW 7</title>
            <engine>V7</engine>
            <dateOfRelease>2021-05-10</dateOfRelease>
        </vehicle>
    </vehicles>
</company>
